# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

backtrace_c <- function(imax) {
    .Call('_ConsSeg_backtrace_c', PACKAGE = 'ConsSeg', imax)
}

#' Calculate consensus segments from a list of segmentation breakpoints
#' @param b list of breakpoints of different segmentations
#' @param n total sequence length 
#' @param w weights vector, must sum up to 1
#' @param store for debugging: store and return all internal vectors
#'@export
consensus_c <- function(b, n, w, store = 0L) {
    .Call('_ConsSeg_consensus_c', PACKAGE = 'ConsSeg', b, n, w, store)
}

