# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

w <- function(m, M) {
    .Call('_ConsSeg_w', PACKAGE = 'ConsSeg', m, M)
}

backtrace_c <- function(imax) {
    .Call('_ConsSeg_backtrace_c', PACKAGE = 'ConsSeg', imax)
}

#' Calculate consensus segments from a list of segmentation breakpoints
#' @param b list of breakpoints of different segmentations
#' @param n total sequence length (\code{max(b)} if not provided)
#' @param w weight function, taking one argument: the index \code{m} of
#' the respective segmentation in the breakpoint list \code{b}
#' @param e potential function, taking one argument: the length \code{L}
#' of the evaluated interval
#' @param store.matrix for debugging: store and return all internal vectors
#'@export
consensus_c <- function(b, n, store_matrix = 0L) {
    .Call('_ConsSeg_consensus_c', PACKAGE = 'ConsSeg', b, n, store_matrix)
}

